image: node:4.2.2

stages:
  - setup
  - build
  - test
  - deploy

cache:
  paths:
  - node_modules/

before_script:
  - apt-get update -qy
  - npm install -g webpack
  - npm install

build:
  stage: build
  script:
    - ls -la
    - npm run client:package

create_docker:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/reallybigtree/pinecone-server .
    - docker push registry.gitlab.com/reallybigtree/pinecone-server

