image: docker:git

stages:
  - test
  - build
  - deploy

before_script:
  - apt-get update -qy
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install -g webpack
  - npm install

build:
  stage: build
  script:
    - npm run client:package

create_staging_docker:
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/reallybigtree/pinecone-server .
    - docker push registry.gitlab.com/reallybigtree/pinecone-server

